import { MainHeader } from '@/components/MainHeader'
import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import { MainFooter } from '@/components/MainFooter'

const inter = Inter({ subsets: ['latin'] })
const poppins= Poppins({weight: ["100", "200", "300", "700"], subsets: ['latin']})

export const metadata = {
  title: 'Aashish Baisla - Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MainHeader/>
        {children}
        <MainFooter/>
      </body>
    </html>
  )
}
